width = 1280
height = 720
fps = 30
background-keep-aspect = no
background-image = "bg.png"
foreground-image = "bg.png"
no-foreground = yes
# no-background = yes
background-blur = 80
webcam-path = /dev/video0
threshold = 50
